### ISSUE TITLE
Cannot login,

### ISSUE THREAD

**Issue by oscarmiza** [open-wa/wa-automate-deploy-railway#1]
I use the deploy button and setup the variables.
The server starts but when I get the first QR and canned. It says tree times 

AUTH SUCCESS
AUTH SUCCESS
AUTH SUCCESS

After 10 min I get the message that I can close the windows and go to the api-docs the soccket is disconnected.

but  if I reload the localhost, has again an QR but it doesn't work. and I don't recive new QR.

{
  "WA_VERSION": "2.2224.8",
  "WA_AUTOMATE_VERSION": "4.42.4",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5060.114",
  "START_TS": 1657584815982,
  "RAM_INFO": "Total: 126.74 GB | Free: 66.11 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true
}

- OS: Linux 4.19
- Node: 18.4.0
- npm: 8.12.1

**Comment by smashah** [comment]
@oscarmiza this is still WIP. Will update you once it's ready

**Comment by oscarmiza** [comment]
Thanks, so much

**Comment by smashah** [comment]
@oscarmiza should be working now - it was a port issue for the finalized easy api. Once scanned and the logs say so, just refresh the browser and you will be forwarded to the api docs. thanks

**Comment by oscarmiza** [comment]
Thanks so much!
