### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by oscarmiza** [open-wa/wa-automate-deploy-railway#2]
Hi, I restart the server and its throwing this errors.

Its configured the same as this project just using another WA-KEY variable instead API-KEY

Starting the application
Using version: latest
./node_modules/@open-wa/wa-automate/bin/server.js --in-docker --qr-timeout 0 --popup --debug --force-port
npm notice
npm notice New minor version of npm available! 8.15.0 -> 8.18.0
npm notice Changelog: <[https://github.com/npm/cli/releases/tag/v8.18.0>](https://github.com/npm/cli/releases/tag/v8.18.0%3E);
npm notice Run `npm install -g npm@8.18.0` to update!
npm notice
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/owauser/.npm/_logs/2022-08-31T14_15_25_361Z-debug-0.log

**Comment by smashah** [comment]
@oscarmiza should be fixed now thanks
